
language: python
notifications:
  email: false
python:
  - 2.7
install:
  - pip install -r pip-sample/requirements.txt
script:
  - echo "no scripts"
after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
