
language: python
notifications:
  email: false
python:
  - 3.7.4
install:
  - pip install -r ./pip-sample/requirements.txt
script:
  - echo "no scripts"
after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
  - bash <(curl -s https://scripts.scantist.com/staging/ci-travis.sh)
