
language: python
notifications:
  email: false
python:
  - 3.4
install:
  - pip install --upgrade pip
  - pip install -r pip-sample/requirements.txt
script:
  - echo "no scripts"
after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
